minor fixes

diff --git a/init-container/Dockerfile b/init-container/Dockerfile
--- a/init-container/Dockerfile
+++ b/init-container/Dockerfile
@@ -1,4 +1,6 @@
 FROM alpine
+# using mirror for packages. main repo is not always available
+# TODO: rm if main become stable
 RUN echo http://dl-5.alpinelinux.org/alpine/v3.7/main > /etc/apk/repositories; \
     echo http://dl-5.alpinelinux.org/alpine/v3.7/community >> /etc/apk/repositories
 
@@ -7,7 +9,7 @@ RUN apk update && apk add openssh && apk add curl && apk add git
 # generate known_host record 
 # check if it was generated, if not exit with error. It means service is not ready or network issue
 # id_rsa generation
-# check if it was generated. (will fail if wolume not mounted etc.)
+# check if it was generated. (will fail if volume not mounted etc.)
 # register system key
 # check curl error code and exit using it (>0 if curl had non 2xx code returned)
 CMD rm -rf ~/.ssh/* && \
@@ -16,7 +18,7 @@ CMD rm -rf ~/.ssh/* && \
     && cat ~/.ssh/known_hosts && ssh-keygen -f ~/.ssh/id_rsa -t rsa -N ""; \
     [ -s ~/.ssh/id_rsa ] || exit 1 \
     curl -X POST http://$GIT_API_HOST/users/customer/$PRODUCER/ssh -d '{"type":"$GIT_KEY_TYPE","publicKey":"'"$(cat ~/.ssh/id_rsa.pub)"'"}'  -H "Content-type: application/json"; \
-    exit $? \
+    exit $? 
 # $GIT_HOST - gitea url 
 # $GIT_API_HOST git-api host
 # $PRODUCER - username
